// Divide and Conquer - countZeroes
// Given an array of 1s and 0s which has all 1s first followed by all 0s,
// write a function called countZeroes, which returns the number of zeroes in the array.

// Time Complexity - O(log n)

// function countZeroes(binaryArr) {
//   let len = binaryArr.length;
//   if (!len) return 0;
//   if (len === 1) return Number(!binaryArr[0]);

//   let start = 0;
//   let end = len - 1;
//   let mid;

//   while (start <= end) {
//     mid = Math.floor((start + end) / 2);

//     //If mid element is 0
//     if (binaryArr[mid] === 0) {
//       //And previous element is 1
//       if (binaryArr[mid - 1] === 1) return len - mid;
//       //Previous element is 0->discard forward array
//       else end = mid - 1;
//     }
//     //Else mid element is 1
//     else {
//       //If next element is 0
//       if (binaryArr[mid + 1] === 0) return len - (mid + 1);
//       //If next element is 1
//       else start = mid + 1;
//     }
//   }
// }
//Original approach, faster for normal cases, but incorrect for edge cases due to arr[mid+1] or arr[mid-1] becoming undefined

function countZeroes(binaryArr) {
  let len = binaryArr.length;
  if (!len) return 0;
  if (len === 1) return Number(!binaryArr[0]);

  let start = 0;
  let end = len - 1;
  let mid;

  while (start <= end) {
    mid = Math.floor((start + end) / 2);
    //Anything other than 0
    if (binaryArr[mid]) start = mid + 1;
    //Only zero
    else end = mid - 1;
  }
  return len - start;
}

//Test cases generated by ChatGPT
// 1️⃣ All ones — no zeroes at all
console.log(countZeroes([1, 1, 1, 1, 1, 1, 1, 1])); // Expected: 0

// 2️⃣ All zeroes — no ones at all
console.log(countZeroes([0, 0, 0, 0, 0, 0, 0, 0])); // Expected: 8

// 3️⃣ Only one element, it's a 1
console.log(countZeroes([1])); // Expected: 0

// 4️⃣ Only one element, it's a 0
console.log(countZeroes([0])); // Expected: 1

// 5️⃣ Transition happens right in the middle
console.log(countZeroes([1, 1, 1, 1, 0, 0, 0, 0])); // Expected: 4

// 6️⃣ Transition happens at the end — just one 0
console.log(countZeroes([1, 1, 1, 1, 1, 1, 1, 0])); // Expected: 1

// 7️⃣ Transition happens early — mostly zeroes
console.log(countZeroes([1, 0, 0, 0, 0, 0, 0, 0])); // Expected: 7

// 8️⃣ Empty array
console.log(countZeroes([])); // Expected: 0

// 9️⃣ Very large array, transition happens near the end
console.log(countZeroes([...Array(9999).fill(1), ...Array(1001).fill(0)])); // Expected: 1001

// 🔟 Trick case — exactly one of each, minimal switch
console.log(countZeroes([1, 0])); // Expected: 1
